import Head from "next/head";
import { useState } from "react";
import ReactMarkdown from "react-markdown";
import useDarkMode from "../hooks/useDarkMode";

export default function Home() {
  const [colorTheme, setTheme] = useDarkMode();
  const [code, setCode] = useState("");
  return (
    <div className="">
      <Head>
        <title>Giga Markdown Editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/1.png" />
      </Head>
      <main className="bg-gray-800 dark:bg-white p-3 flex justify-between max-h-screen min-h-screen">
        <div className="bg-black w-6/12 rounded-xl m-5 ">
          <textarea
            cols="30"
            rows="30"
            onChange={(e) => setCode(e.target.value)}
            className="resize-none outline-none text-gray-50 bg-black p-5 rounded-xl w-full h-full"
          ></textarea>
        </div>
        <div className="bg-gray-50 dark:bg-[#222B45] w-6/12 rounded-xl p-5 pt-2 m-5 overflow-y-scroll">
          {colorTheme === "light" ? (
            <svg
              onClick={() => setTheme("light")}
              xmlns="http://www.w3.org/2000/svg"
              className="h-6 w-6 text-white"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
              />
            </svg>
          ) : (
            <svg
              onClick={() => setTheme("dark")}
              xmlns="http://www.w3.org/2000/svg"
              className="h-6 w-6"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"
              />
            </svg>
          )}
          <div className="prose prose-lg  dark:prose-headings:text-gray-50 dark:prose-p:text-gray-200 dark:prose-strong:text-white dark:prose-a:text-white prose-a:underline dark:prose-ol:text-gray-100 dark:prose-ul:text-gray-100 prose-img:rounded-xl dark:prose-table:text-gray-100 dark:prose-em:text-gray-100 break-words my-5">
            <ReactMarkdown>{code}</ReactMarkdown>
          </div>
        </div>
      </main>
    </div>
  );
}
